volumes:
    langgraph-data:
        driver: local
services:
    langgraph-redis:
        image: redis:6
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 1s
            retries: 5

    langgraph-postgres:
        image: postgres:16
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - langgraph-data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U postgres
            start_period: 10s
            timeout: 1s
            retries: 5
            interval: 5s
    langgraph-api:
        build:
            context: ./
            dockerfile: ./lanchain-api.Dockerfile
        image: ollama-deep-researcher:0.0.2
        restart: always
        ports:
            - "2024:2024"                                      #<===== NOTE this change
        depends_on:
            langgraph-redis:
                condition: service_healthy
            langgraph-postgres:
                condition: service_healthy
        environment:
            REDIS_URI: redis://langgraph-redis:6380
            LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
            POSTGRES_URI: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable
            LLM_PROVIDER: ${LLM_PROVIDER}
            OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
            TAVILY_API_KEY: ${TAVILY_API_KEY}
            MAX_WEB_RESEARCH_LOOPS: ${MAX_WEB_RESEARCH_LOOPS}
            FETCH_FULL_PAGE: ${FETCH_FULL_PAGE}
            SEARCH_API: ${SEARCH_API}
            LOCAL_LLM: ${LOCAL_LLM}
            GROQ_API_KEY: ${GROQ_API_KEY}
            GROQ_LLM: ${GROQ_LLM}
            GROQ_API_BASE: ${GROQ_API_BASE}
        volumes:
            - /dev/shm:/dev/shm
        user: "appuser"