volumes:
    langgraph-data:
        driver: local
services:
    langgraph-redis:
        image: redis:8
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 1s
            retries: 5

    langgraph-postgres:
        image: postgres:17
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - langgraph-data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U postgres
            start_period: 10s
            timeout: 1s
            retries: 5
            interval: 5s
    langgraph-api:
        build:
            context: ./
            dockerfile: ./lanchain-api.Dockerfile
            args:
                - DOCKER_BUILDKIT=1
                - COMPOSE_DOCKER_CLI_BUILD=1
            target: runtime
        image: d_rag:0.1.0
        restart: always
        ports:
            - "2024:2024"                                      #<===== NOTE this change
        depends_on:
            langgraph-redis:
                condition: service_healthy
            langgraph-postgres:
                condition: service_healthy
        environment:
            REDIS_URI: redis://langgraph-redis:6380
            LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
            POSTGRES_URI: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable
            LLM_PROVIDER: ${LLM_PROVIDER}
            OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
            MAX_WEB_RESEARCH_LOOPS: ${MAX_WEB_RESEARCH_LOOPS}
            LOCAL_LLM: ${LOCAL_LLM}
            GROQ_API_KEY: ${GROQ_API_KEY}
            GROQ_LLM: ${GROQ_LLM}
            GROQ_API_BASE: ${GROQ_API_BASE}
            OPENAI_API_BASE: ${OPENAI_API_BASE}
            OPENAI_API_KEY: ${OPENAI_API_KEY}
            OPENAI_LLM: ${OPENAI_LLM}
        volumes:
            - /dev/shm:/dev/shm